name: Build documentation

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2024-02-19

    env:
      # Directory that will be published on github pages
      PUBLISH_DIR: ./_build/html

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r requirements-docs.txt

      - name: Build docs
        run: jupyter book build -W .

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/_build
          key: cache_v1
          restore-keys: |
            cache_v1

      - name: Install dependencies
        run: python3 -m pip install -r requirements-docs.txt

      - name: Build docs
        run: jupyter book build .

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.PUBLISH_DIR }}
          name: documentation
